perf: sumac release support
eduNEXT/eox-hooks pull request #70
Opened 2024-12-12 22:32 UTC by luisfelipec95

## Description

This PR aims to support the new Sumac Release

## Testing instructions

1, Create a Sumac environment using Tutor or TVM.
2. Install eox-hooks using this branch you can follow the official [tutor documentation](https://docs.tutor.overhang.io/configuration.html#installing-extra-xblocks-and-requirements).
3. Follow the [test cases ](https://docs.google.com/document/d/1f7LkXyxUbBcAdkDsWhtEzNfVNFFmV65enpKrEUUnirw/edit?tab=t.0)file.

2024-12-19 15:56 UTC, luisfelipec95 commented
The test cases have already been tested in the remote sumac environment

2024-12-20 14:20 UTC, magajh commented
@luisfelipec95 as the doc suggests, you need to review and merge the dependabots PRs as well, so we can keep our workflows updated https://github.com/eduNEXT/eox-hooks/pull/68

2024-12-20 14:24 UTC, magajh requested changes
@luisfelipec95 
we need to update the setup.py file
https://github.com/eduNEXT/eox-hooks/blob/master/setup.py#L80

Also, it's very important to always check the constraints in the project. In this case I believe, since we are removing the support for Python 3.8, that this constraint is no longer needed: https://github.com/eduNEXT/eox-hooks/blob/master/requirements/constraints.txt#L20-L21
So we need to remove it and then run `make upgrade` for the requirements

2024-12-20 14:24 UTC, magajh commented on README.rst
>  +---------------------+----------------+
Since we are dropping support for python 3.8, we need to add the constraint in the compatibility table for Quince < 8.0.0

2024-12-20 17:22 UTC, magajh approved these changes
LGTM

2024-12-23 23:40 UTC, jignaciopm approved these changes
@luisfelipec95 @magajh I have tried the [test cases](https://docs.google.com/document/d/1f7LkXyxUbBcAdkDsWhtEzNfVNFFmV65enpKrEUUnirw/edit?tab=t.0) in the instance https://tenant-a.sumac.releases.edunext.link/ and all the results were successful.

2024-12-26 13:51 UTC, merged